matches:
  - trigger: "exp:ssr"
    replace: "server-side rendering (SSR)"
  - trigger: "exp:spa"
    replace: "single page application (SPA)"
  - trigger: "exp:rls"
    replace: "row level security (RLS)"
  - trigger: "exp:erd"
    replace: "Entity Relationship Diagram (ERD)"
  - trigger: "exp:pkce"
    replace: "Proof Key for Code Exchange (PKCE)"
  - trigger: "exp:jwt"
    replace: "JSON Web Token (JWT)"
  - trigger: "exp:mfa"
    replace: "Multi-factor authentication (MFA)"
  - trigger: "exp:otp"
    replace: "One-time password (OTP)"
  - trigger: "exp:wal"
    replace: "Write Ahead Log (WAL)"
  - trigger: "exp:llm"
    replace: "large language model (llm)"
  - trigger: "exp:slm"
    replace: "small language model (slm)"

