matches:
  - trigger: "exp:ssr"
    replace: "server-side rendering (SSR)"
  - trigger: "exp:spa"
    replace: "single page application (SPA)"
  - trigger: "exp:rls"
    replace: "row level security (RLS)"
  - trigger: "exp:erd"
    replace: "Entity Relationship Diagram (ERD)"
  - trigger: "exp:pkce"
    replace: "Proof Key for Code Exchange (PKCE)"